---
system_banner_message: |
  ***************************************************************************
                           SECURITY WARNING:
      This system is for the exclusive use of authorized users.
      All activity on this server is monitored and recorded.
      Unauthorized access will be prosecuted.
  ***************************************************************************
